### ISSUE TITLE
David B -05 review -- 6 Non-Queue-Building PHB Requirements

### ISSUE THREAD

**Issue by thomas-fossati** [gwhiteCL/NQBdraft#13]
A node supporting the NQB PHB MUST provide a queue for non-queue-
   building traffic separate from the queue used for queue-building
   traffic.
s/separate from the queue/separate from any queue/ as there may be more than one such queue.
 
      The NQB queue SHOULD be given equal priority compared to queue-
   building traffic of equivalent importance.
I understand the intent, but I don't think that "equal priority" is the right choice of words because more than priority is involved.  Something like "equivalent forwarding preference" seems closer to the mark.
 
   A node supporting the NQB PHB SHOULD treat traffic marked as Default
   (DSCP=0) as QB traffic having equivalent importance to the NQB marked
   traffic. 
[**] That may not work out well for the 42 DSCP.  Needs some rethinking.
 
   A node supporting the NQB PHB SHOULD treat traffic marked as Default
   (DSCP=0) as QB traffic having equivalent importance to the NQB marked
   traffic.  A node supporting the NQB DSCP MUST support the ability to
   configure the classification criteria that are used to identify QB
   and NQB traffic having equivalent importance.
Second sentence doesn't parse for me.  Do the criteria have equivalent importance or do the two types of traffic?
 
   The NQB queue SHOULD have a buffer size that is significantly smaller
   than the buffer provided for QB traffic.  It is expected that most QB
   traffic is optimized to make use of a relatively deep buffer (e.g. on
   the order of tens or hundreds of ms) in nodes where support for the
   NQB PHB is advantageous (i.e. bottleneck nodes).  Providing a
   similarly deep buffer for the NQB queue would be at cross purposes to
   providing very low queueing delay, and would erode the incentives for
   QB traffic to be marked correctly.
Add an example of time-duration size of NQB queue – e.g., single-digit ms, sub-ms?

**Comment by gwhiteCL** [comment]
addressed [**] in draft-07
