### ISSUE TITLE
Questions & comments from Dan

### ISSUE THREAD

**Issue by thomas-fossati** [gwhiteCL/NQBdraft#20]
1.	Section 4: This section provides a couple of reasons why it has been difficult with existing DiffServ architecture to meet end-to-end performance requirements, especially issues related to all networks in the path not agreeing to performance requirements of an application. With NQB PHB, separate DiffServ codes are defined so that packets from NQB flows can essentially avoid getting backlogged with QB flows in the same queues. But what about performance requirements associated with NQB flows? Is having separate NQB queues sufficient to meet end-to-end performance requirements? While having separate queues for NQB flows will definitely help, is that enough to overcome the issue of all networks in the path not agreeing to performance requirements? In other words, would some sort of end-to-end agreement still be required across all networks in the path, albeit in a simpler form?

2.	Section 6: This section indicates, that the node should provide a scheduler, which allows QB and NQB traffic of equivalent importance to share the link in a fair manner, e.g. a deficit round-robin scheduler with equal weights. Is it fair to assume that the scheduler would allow NQB traffic of higher importance to get more prioritized scheduling treatment. For example, two NQB flows may have different latency requirements wrt each other as well as wrt to other QB traffic. In such a case, would the NQB flow with tighter latency requirement be able to get prioritized scheduling treatment? The answer to this may simply fall back to how current DiffServ architecture treats flows with different priorities. But that is exactly where the end-to-end issue from previous question comes in.

3.	Section 11.2: Again, there could be some discussion here related to per-flow QoS for 5G. For example, even though an NQB flow is assigned to the same ‘default’ non-GBR bearer as a QB flow, it could be assigned a different flow ID so that it could be provided more QoS-specific treatment (although still non-GBR, but potentially with higher priority weighting, e.g. QCI7).

**Comment by gwhiteCL** [comment]
On item 1, NQB is intended for the prevalent situation where the performance requirements of applications cannot be assured, and as a result, applications cannot feasibly place requirements on the network. Instead, many applications have evolved to make the best out of the network environment that they find themselves in.  In this context, NQB provides a better network environment for applications that send data at relatively low data rates.

**Comment by gwhiteCL** [comment]
On item 2, the NQB PHB provides a single importance class or priority.  But, e0adc17 (draft-17) did add a statement that provides a suggestion on a way in which this could be handled: 

> While not fully described in this document, it may be possible for network equipment to implement a separate QB/NQB pair of queues for additional service classes beyond the Default PHB / NQB PHB pair.

**Comment by gwhiteCL** [comment]
On item 3, I'm not enough of a 5G expert to craft text to address this comment.  I would appreciate any suggestions.

**Comment by gwhiteCL** [comment]
@thomas-fossati I'd appreciate your view on item 3 from Dan's comments.  Do you think a change is needed to address this?

**Comment by gwhiteCL** [comment]
From @thomas-fossati :

> The comment was filed against version -06 of the draft.  In the meantime, it looks like we addressed that already [1].  In §8.2, first para, last sentence [2], we now say:
>  
> The 5G radio and core systems offer more flexibility over bearer allocation, meaning bearers can be allocated per traffic type (e.g., loss-tolerant, low-latency etc.) and hence support more suitable treatment of Internet real-time flows.
>  
> [1] https://author-tools.ietf.org/iddiff?url1=draft-ietf-tsvwg-nqb-06&url2=draft-ietf-tsvwg-nqb-18&difftype=--hwdiff
> [2] https://www.ietf.org/archive/id/draft-ietf-tsvwg-nqb-18.html#section-8.2-1
>
