### ISSUE TITLE
Move non-compliance topics to a separate section or appendix

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#26]
https://mailarchive.ietf.org/arch/msg/tsvwg/W7NNUE-sEb3hOJC5k0V41Nvzj1c/

> 19. The following text is still to me is problematic for a PS.
> /Similarly, networks and nodes that aggregate service classes as discussed in
> [RFC5127] and [RFC8100] might not be able to provide a PDB/PHB that
> meets the requirements of this document./
> - We can define in this PS, what is to be done to comply with the PS, we
> should not provide text that seems to hint that complying with the spec
> allows non-compliance.
> - This text needs to be in a separate section to clearly differentiate
> it from the other treatment
>
> [GW] I see your point.  How separate does it need to be?  An appendix?

[GF2] Moving some discussion of considerations there might work, it would be a good start.

**Comment by gwhiteCL** [comment]
I'm struggling with how to respond to this.  The text quoted is in the DSCP marking section, in a subsection that talks about configurations that a network operator could employ in order to provide NQB service, including how to handle situations where some of the network gear does not support the PHB.  Is it really that objectionable to discuss this in the main body?  I can move the offending sentences to an appendix, but it looks to me like it will be sort of cumbersome to do so (repeating context, etc.).

**Comment by gorryfair** [comment]
I see the start of 4.2 says forward with default. That I understood.

 I found the section confusing.

In this case, it is the discussion of controlled environments within the same section is the root problem,
/Similarly, networks and nodes that aggregate service classes as discussed in
[RFC5127] and [RFC8100] might not be able to provide a PDB/PHB that
meets the requirements of this document./
... I do not understand are you saying with respect to [RFC5127] and [RFC8100]... but if this relates only to controlled environments, it might be easier to read?

You then seem to go-on to make a recommendation (which ought to be written as a SHOULD),
  / In these cases it is RECOMMENDED that traffic marked
   with the NQB DSCP be aggregated into the Elastic Treatment Aggregate
   (for [RFC5127] networks) or the Default / Elastic Treatment Aggregate
   (for [RFC8100] networks), although in some cases a network operator
   might instead choose to aggregate NQB traffic into the (Bulk) Real-
   Time Treatment Aggregate./
- which is a strong( if guarded statement ) ? If this normative language  is needed within the PS, we need to look carefully at this.

Whereas the statement: /DSCP SHOULD be preserved/ is more clear. (Note: That ought to be a separate para, because it is a different requirement). Doesn't that apply to both types of aggregation?

**Comment by gwhiteCL** [comment]
Ok, I've reorganized the material in that section to reduce the number of twists and turns.  Does this address your concerns or does it still need more work?

> It is RECOMMENDED that networks and nodes that do not support the NQB PHB be configured to treat traffic marked with the NQB DSCP the same as traffic with the "Default" DSCP. This includes networks and nodes that aggregate service classes as discussed in [RFC5127] and [RFC8100], in which case this recommendation would result in traffic marked with the NQB DSCP being aggregated into the Elastic Treatment Aggregate (for [RFC5127] networks) or the Default / Elastic Treatment Aggregate (for [RFC8100] networks).
> 
> In nodes that do not typically experience congestion (for example, many backbone and core network switches), forwarding packets with the NQB DSCP using the Default treatment might be sufficient to preserve loss/latency/jitter performance for NQB traffic.
> 
> In nodes that do frequently experience congestion, forwarding packets with the NQB DSCP using the Default treatment could result in degradation of loss/latency/jitter performance but nonetheless preserves the incentives described in [Section 5]. An alternative would be to aggregate traffic marked with the NQB DSCP with real-time, latency sensitive traffic (e.g. the (Bulk) Real-Time Treatment Aggregate), although this risks creating an incentive for mismarking of non-compliant traffic as NQB and should only be considered in environments where this risk is acceptable.
> 
> It is additionally RECOMMENDED that networks and nodes that do not support the NQB PHB simply classify packets with the NQB DSCP value into the appropriate treatment aggregate, or encapsulate such packets, rather than re-marking them with a different DSCP. This preservation of the NQB DSCP value enables hops further along the path to provide the NQB PHB successfully. This aligns with recommendations in [RFC5127].


I'm not totally happy with the "where this risk is acceptable" wording, but haven't come up with a suitably concise way of saying it that covers all of the cases (e.g. where DSCP marking compliance is controlled by an administrator, or where the benefits of the real-time treatment aggregate don't create much of an incentive, or where a terrific traffic protection algorithm has been put in place, or where the network operator will monitor for abuse in some other way).

**Comment by gwhiteCL** [comment]
I went ahead and merged the changed text above into the main line in the repo. If there are further comments, we can make additional changes.

**Comment by gwhiteCL** [comment]
In place of the sentence that ends with "where this risk is acceptable", how about:

> An alternative would be to aggregate traffic marked with the NQB DSCP with real-time, latency sensitive traffic (e.g. the (Bulk) Real-Time Treatment Aggregate), although this risks creating an incentive for mismarking of non-compliant traffic as NQB and so is NOT RECOMMENDED in general.

Or, I could simply delete that sentence.

**Comment by gwhiteCL** [comment]
Further commits to address these comments in:
https://github.com/gwhiteCL/NQBdraft/commit/cc57136436bcc6081780f54957b6844a429da9a0
https://github.com/gwhiteCL/NQBdraft/commit/a0f4d61a3edab3dd532d94ee92bfa78eda9e58eb
https://github.com/gwhiteCL/NQBdraft/commit/17efbed8be4d1d7f492c563b082a64c889282df4

**Comment by gorryfair** [comment]
Some suggested wording options:
1. Simply deleting the sentence is OK:-)
2. alternatively, perhaps we could say / A configuration that aggregates traffic marked with the NQB DSCP with real-time, latency sensitive traffic (e.g. the (Bulk) Real-Time Treatment Aggregate), needs to first consider the risk of creating an incentive for non-compliant traffic to be mis-marked as NQB./

**Comment by gwhiteCL** [comment]
Thanks for the suggestion.  I would prefer to keep the statement since it is something that I could imagine an operator considering. Your option 2 has some goodness (though I'm not sure how a "configuration" can "consider" anything).  Would this work?

> Aggregating traffic marked with the NQB DSCP into a PHB designed for real-time, latency sensitive traffic (e.g. the (Bulk) Real-Time Treatment Aggregate), might better preserve loss/latency/jitter performance in the presence of congestion, but would need to be done with consideration of the risk of creating an incentive for non-compliant traffic to be mis-marked as NQB.

**Comment by gorryfair** [comment]
That proposal appears to avoid having the last part of this issue.
Together the proposed set of changes resolve the issue that I raised, please do this.
