### ISSUE TITLE
Low-Rate links - combine with guidance for controlled environments?

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#29]
https://mailarchive.ietf.org/arch/msg/tsvwg/TEExPUudk8X5fw9F9vtGD--OwoU/

> 36. Section 5.3 says it provides
> /Guidance for Very Low-Rate Links/
> - I am doubtful that people providing 10 Mbps service would regard their service as
> - I'll reiterate that I really felt uncomfortable with labeling this as /very low rate/. The title here is clearly not likely to attract the  reader who needs to pay a lot of attenetion to this section. In some places in the world 10 Mbps would still be regarded as high speed!!
>
> [GW] One thought would be to call this section something like "Applicability of the NQB PHB" and then this could be a home for the current 4.3.1 and the "controlled environments" material. Would that be a logical structure in your view?

[GF2] I think the section title should be chosen to encourage the correct people to read - just as security considerations makes security people take notice, so we need something that makes people deploying/configuring diffserv take notice.

**Comment by gwhiteCL** [comment]
Ok, in the commit above, I moved this subsection into the "Configuration and Management" section, and renamed it: "Guidance for Lower-Rate Links".  I also added some more text to explain how an operator might configure a larger burst tolerance, and made the requirement statements a bit more standalone.

**Comment by gorryfair** [comment]
Looks like an improvement, please resolve it this way.
