### ISSUE TITLE
Need to better describe the differences between EF and NQB

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#32]
https://mailarchive.ietf.org/arch/msg/tsvwg/UTR74bpFzaUULGD0bhZzxq0CT1c/
https://mailarchive.ietf.org/arch/msg/tsvwg/IxvY0N8faDxqyaYuYc_zz6gedog/

**Comment by gorryfair** [comment]
Note also this, which could be helpful (from RG): "- The EF PHB is defined as a forwarding treatment for a particular diffserv aggregate where the departure rate of the aggregate's packets from any diffserv node must equal or exceed a configurable rate. The EF traffic SHOULD receive this rate independent of the intensity of any other traffic attempting to transit the node. 
- It SHOULD average at least the configured rate when measured over any time interval equal to or longer than the time it takes to send an output link MTU sized packet at the configured rate. 
- The configured minimum rate MUST be settable by a network administrator (using whatever mechanism the node supports for non-volatile configuration).
 - If the EF PHB is implemented by a mechanism that allows unlimited preemption of other traffic (e.g., a priority queue), the implementation MUST include some means to limit the damage EF traffic could inflict on other traffic (e.g., a token bucket rate limiter).
- This maximum EF rate, and burst size if appropriate, MUST be settable by a network administrator (using whatever mechanism the node supports for non-volatile configuration)."

**Comment by gorryfair** [comment]
And this from my note the tsvwg thread: 

"In terms of  DiffServ Service Classes, the proposal is that NQB traffic is treated as a part of the Default treatment.
Capacity assigned to this class is not prioritised with respect to other classes, AFxx, EF, etc. Of course, Default traffic (i.e. part of the the Best Effort Access Category) marked as NQB could be prioritised with respect to LE.  (i.e.  the NQB "queue" would be emptied in a priority sequence before the LE "queue")."

**Comment by gwhiteCL** [comment]
added text to address this issue in 
https://github.com/gwhiteCL/NQBdraft/commit/1e859f90fb5168c513b06797d1e7fd961498d111
https://github.com/gwhiteCL/NQBdraft/commit/93ecaf417b4e0ff297a2f2d43d2c344fbb74d5ec
https://github.com/gwhiteCL/NQBdraft/commit/c98be1a956bf0a1e1a75c72f6c078afa52916bc0
