### ISSUE TITLE
NQB updates to RFC8325 should point to UPs not ACs

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#38]
NQB intends to update the DSCP-to-UP guidance provided in RFC8325, yet it doesn't directly provide that guidance for the NQB DSCP. Instead it provides a DSCP-to-AC recommendation.  This should be fixed to be consistent.

**Comment by kiwinp** [comment]
Proposed Text:
In addition to the requirements provided in other sections of this document, to support the NQB PHB, 
Wi-Fi equipment (including equipment compliant with [RFC8325]) SHOULD map the NQB DSCP 45 (decimal) 
into a separate queue in the Video Access Category. It is RECOMMENDED that Wi-Fi equipment provide 
a separate queue in UP 5, and map the NQB DSCP 45 (decimal) to that queue.

Justification:
- Wi-Fi networks now and in the foreseeable future do categorize different services
- Existing service applications (e.g. Telephony, multimedia conferencing, voice-admit, etc) are using their currently assigned DSCP/UP/AC values in section 4.3 RFC8325 https://www.rfc-editor.org/rfc/rfc8325.html#section-4.3 that map to UP_5 and UP_6
- NQB microflows meet the criteria for AC_VI
- UP_5 is the recommendation in IEEE contribution https://mentor.ieee.org/802.11/dcn/23/11-23-0679-00-0uhr-low-latency-qos-based-on-l4s.pptx
- UP_5 is the recommendation in https://github.com/jlivingood/IETF-L4S-Deployment/blob/main/Network-Config-Guide.md

**Comment by gwhiteCL** [comment]
Thanks for the comment.  The NQB PHB is defined as a shallow-buffered best effort service that is offered as an alternative to a default deep-buffered best effort service.  The decision to leverage AC_VI in existing Wi-Fi networks is described in https://www.ietf.org/archive/id/draft-ietf-tsvwg-nqb-19.html#section-7.3.1, but the intention is that future gear maps DSCP=45 to a separate queue in AC_BE.

**Comment by kiwinp** [comment]
For applications comfortable with Best Effort, that should work.
