### ISSUE TITLE
comments on -20

### ISSUE THREAD

**Issue by gregbo** [gwhiteCL/NQBdraft#41]
These comments are generally editorial.  If you wish, I can submit a PR for the text substitutions.

- Use a consistent spelling for the following words and phrases: prioritize, queuing, judgment, out-of-order
- In line 134, assuming 'LE' stands for 'lower-effort', indicate as such, and cite RFC 8622

Also, provide these text substitutions at the given lines:

154: s/NQP/NQB/
156: s/applications generation/applications generating/
158: s/DSCP value/DSCP values/
190: s/An operator would need to use their own judgement based on the actual traffic characteristics in their network/Operators would need to use their own judgement based on the actual traffic characteristics in their networks/
235: s/that are used classify packets/that are used to classify packets/
376: s/If a Non-Queue-Building microflow were to fail/If a Non-Queue-Building microflow was to fail/
511: s/non capacity-seeking/non-capacity-seeking/

**Comment by gwhiteCL** [comment]
Thanks @gregbo, I went ahead and made these changes.

On 158, I assume you are referring to the second instance of "DSCP value" not the first.

On "out-of-order" vs. "out of order", it looks better to my eye to use the hyphenated version when it precedes "delivery" (i.e. "out-of-order delivery"), but to not hyphenate it when it follows "delivered"  (i.e. "delivered out of order").  So, I applied that rule consistently.  But, I'm willing to make them all one way or the other if anyone has a strong objection.
