### ISSUE TITLE
mention that it is reasonable to expect ISPs to manage the forwarding of DSCPs into their customers' networks

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#52]
From: https://mailarchive.ietf.org/arch/msg/tsvwg/ujZCuex6g6zfWCd0jxB-8OfQCBY/

per @dlb237:
>> A. For inbound NQB traffic, the ISP has available tools (e.g., bleaching DSCP 45 to zero) to control the impacts of DSCP 45, as Greg has explained. 
 
> The two of us agree on the technical aspects, namely that the ISP has available tools.  What remains is how to discuss those available tools, which is editorial.  It would be helpful if the edits provided some rationale for why it’s reasonable to expect the ISP to use those tools even though the ISP does not support NQB – part of the rationale is likely to be that some use of those tools is already required in practice, e.g., to prevent large amounts of CS6 and CS7 traffic from being sent into customer networks.
 
[GW2] Ok.  I can work up some editorial changes.

**Comment by gwhiteCL** [comment]
The current text in the draft that discusses this is:

> For application traffic that originates outside of the Wi-Fi network, and thus is transmitted by the Access Point, the choice of DSCP 45 does create a potential for abuse by non-compliant applications. But, opportunities exist in the network components upstream of the Wi-Fi Access Point to police the usage of the NQB DSCP and potentially re-mark traffic that is considered non-compliant, as is recommended in [Section 4.4.1](https://www.ietf.org/archive/id/draft-ietf-tsvwg-nqb-25.html#unmanaged). Furthermore, it is a common practice for residential ISPs to re-mark the Diffserv field to zero on all traffic destined to their customers' networks, and any change to this practice done to enable the NQB DSCP to pass through could be done alongside the implementation of the recommendations in [Section 4.4.1](https://www.ietf.org/archive/id/draft-ietf-tsvwg-nqb-25.html#unmanaged).

**Comment by gwhiteCL** [comment]
I suggest replacing the last sentence with:
> Furthermore, it is reasonable to expect that ISPs currently manage the DSCPs on traffic destined to their customers' networks, and will continue to do so whether they support NQB or not.  This includes the common practice in residential broadband networks of re-marking the Diffserv field to zero on all traffic. Any change to these practices done to enable the NQB DSCP to pass through could be done alongside the implementation of the recommendations in [Section 4.4.1](https://www.ietf.org/archive/id/draft-ietf-tsvwg-nqb-25.html#unmanaged).


@dlb237 Do we need to provide further explanation for why this is reasonable, e.g., to prevent large amounts of CS6 and CS7 traffic from being sent into customer networks? Or is this sufficient?

**Comment by dlb237** [comment]
Yes, that’ll suffice, and it’s more concise than anything I might have written.  Thanks, --David
