### ISSUE TITLE
Provide further explanation regarding upstream AC_VI usage

### ISSUE THREAD

**Issue by gwhiteCL** [gwhiteCL/NQBdraft#53]
We currently have the bullet list in §7.3.1 that discusses all of the rationales for choosing AC_VI, which includes:
 

- Traffic that is compliant with the NQB sender requirements [Section 4.1] is unlikely to cause more degradation to lower priority Access Categories than the existing recommended Video Access Category traffic types: Broadcast Video, Multimedia Streaming, Multimedia Conferencing from [RFC8325], and AudioVideo, ExcellentEffort from [QOS_TRAFFIC_TYPE].

To further address @dlb237's comments regarding upstream usage in Wi-Fi networks that aren't NQB-aware, perhaps we can modify this bullet to add the text in _**bold italics**_ below:
 

- Traffic that is compliant with the NQB sender requirements [Section 4.1] is _**expected to cause minimal degradation to traffic in lower priority Access Categories, and in any case would be**_ unlikely to cause more degradation to lower priority Access Categories than the existing recommended Video Access Category traffic types: Broadcast Video, Multimedia Streaming, Multimedia Conferencing from [RFC8325], and AudioVideo, ExcellentEffort from [QOS_TRAFFIC_TYPE].

**Comment by gorryfair** [comment]
That text is OK with me.

**Comment by gwhiteCL** [comment]
closing as complete
