### ISSUE TITLE
David B -05 review -- 3 Non Queue-Building Behavior

### ISSUE THREAD

**Issue by thomas-fossati** [gwhiteCL/NQBdraft#8]
These applications do not cause queues
   to form in network buffers, but nonetheless can be subjected to
 
That's not strictly correct, but it's close.  A word such as "standing" or "persistent" ought to be inserted between "cause" and "queues to form" as NQB traffic can form short-lived queues that quickly drain.  A similar word insertion change is also wanted here (before "queues"):
 
   ... as a result of sharing a network
   buffer with applications that do cause queues to form

**Comment by gwhiteCL** [comment]
addressed in draft-06 & draft-07
